#!/usr/bin/env bash
set -e

pip install --no-cache-dir aind-codeocean-api==0.2.4
pip install --no-cache-dir aind-data-access-api[secrets,docdb]==0.6.1
pip install --no-cache-dir python-dotenv==1.0.0
pip install --no-cache-dir pytz==2023.3
