name: Tag and publish
on:
  push:
    branches:
      - main
jobs:
  tag:
    uses: AllenNeuralDynamics/aind-github-actions/.github/workflows/tag.yml@main
    secrets:
      SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
